### ISSUE TITLE
ImportError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by felipemouradev** [9e15/net-9e15-nominatim-docker#23]
/srv/nominatim/Nominatim/nominatim/nominatim.py:307: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "Unreachable code")
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim/nominatim/nominatim.py", line 31, in <module>
    import psycopg2
ImportError: No module named 'psycopg2'
string(33) "error status 1 running nominatim!"
ERROR: error status 1 running nominatim!

**Comment by saketbairoliya2** [comment]
Any updates on above error message, I'm also getting similar issue.

**Comment by rockdrigoma** [comment]
I've got same issue. 

```
File "/srv/nominatim/Nominatim/nominatim/nominatim.py", line 31, in <module>
    import psycopg2
ImportError: No module named 'psycopg2'
string(33) "error status 1 running nominatim!"
ERROR: error status 1 running nominatim!
```
@merlinnot @rymain any idea?

**Comment by rymain** [comment]
check my fork here https://github.com/rymain/nominatim-docker/commits/master and changes in the commits, some might help you with the issue
